[package]
name = "capsule"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "capsule"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
tokio.workspace = true
assets.workspace = true
ui = { path = "../ui" }
services = { path = "../services" }
chrono.workspace = true
libc = "0.2"
