[package]
name = "Capsule"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "Capsule"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
tokio.workspace = true
assets.workspace = true
ui = { path = "../ui" }
services = { path = "../services" }
chrono.workspace = true