[package]
name = "services"
version = "0.1.0"
edition = "2024"

[lib]
name = "services"
path = "src/services.rs"

[dependencies]
gpui = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
dirs = { workspace = true }
zbus = "5.18.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
sha2 = "0.10"
chrono = { workspace = true }
regex = "1.10"
arc-swap = "1.7"
futures = "0.3"

niri-ipc.workspace = true
hyprland.workspace = true
